CREATE TABLE players (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE,
    hcim_rank INTEGER
);

CREATE TABLE skills (
    id INTEGER PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE
);

CREATE TABLE activities (
    id INTEGER PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE
);

CREATE TABLE player_skills (
    player_id INTEGER NOT NULL,
    skill_id INTEGER NOT NULL,
    rank INTEGER NOT NULL,
    level INTEGER NOT NULL,
    xp BIGINT NOT NULL,

    PRIMARY KEY (player_id, skill_id),

    FOREIGN KEY (player_id)
        REFERENCES players(id),

    FOREIGN KEY (skill_id)
        REFERENCES skills(id)
);

CREATE TABLE player_activities (
    player_id INTEGER NOT NULL,
    activity_id INTEGER NOT NULL,
    rank INTEGER NOT NULL,
    score BIGINT NOT NULL,

    PRIMARY KEY (player_id, activity_id),

    FOREIGN KEY (player_id)
        REFERENCES players(id),

    FOREIGN KEY (activity_id)
        REFERENCES activities(id)
);

INSERT INTO skills (id, name) VALUES
(0, 'Overall'),
(1, 'Attack'),
(2, 'Defence'),
(3, 'Strength'),
(4, 'Hitpoints'),
(5, 'Ranged'),
(6, 'Prayer'),
(7, 'Magic'),
(8, 'Cooking'),
(9, 'Woodcutting'),
(10, 'Fletching'),
(11, 'Fishing'),
(12, 'Firemaking'),
(13, 'Crafting'),
(14, 'Smithing'),
(15, 'Mining'),
(16, 'Herblore'),
(17, 'Agility'),
(18, 'Thieving'),
(19, 'Slayer'),
(20, 'Farming'),
(21, 'Runecraft'),
(22, 'Hunter'),
(23, 'Construction'),
(24, 'Sailing');

INSERT INTO activities (id, name) VALUES
(0, 'Grid Points'),
(1, 'League Points'),
(2, 'Deadman Points'),
(3, 'Bounty Hunter - Hunter'),
(4, 'Bounty Hunter - Rogue'),
(5, 'Bounty Hunter (Legacy) - Hunter'),
(6, 'Bounty Hunter (Legacy) - Rogue'),
(7, 'Clue Scrolls (all)'),
(8, 'Clue Scrolls (beginner)'),
(9, 'Clue Scrolls (easy)'),
(10, 'Clue Scrolls (medium)'),
(11, 'Clue Scrolls (hard)'),
(12, 'Clue Scrolls (elite)'),
(13, 'Clue Scrolls (master)'),
(14, 'LMS - Rank'),
(15, 'PvP Arena - Rank'),
(16, 'Soul Wars Zeal'),
(17, 'Rifts closed'),
(18, 'Colosseum Glory'),
(19, 'Collections Logged'),
(20, 'Abyssal Sire'),
(21, 'Alchemical Hydra'),
(22, 'Amoxliatl'),
(23, 'Araxxor'),
(24, 'Artio'),
(25, 'Barrows Chests'),
(26, 'Brutus'),
(27, 'Bryophyta'),
(28, 'Callisto'),
(29, 'Calvar''ion'),
(30, 'Cerberus'),
(31, 'Chambers of Xeric'),
(32, 'Chambers of Xeric: Challenge Mode'),
(33, 'Chaos Elemental'),
(34, 'Chaos Fanatic'),
(35, 'Commander Zilyana'),
(36, 'Corporeal Beast'),
(37, 'Crazy Archaeologist'),
(38, 'Dagannoth Prime'),
(39, 'Dagannoth Rex'),
(40, 'Dagannoth Supreme'),
(41, 'Deranged Archaeologist'),
(42, 'Doom of Mokhaiotl'),
(43, 'Duke Sucellus'),
(44, 'General Graardor'),
(45, 'Giant Mole'),
(46, 'Grotesque Guardians'),
(47, 'Hespori'),
(48, 'Kalphite Queen'),
(49, 'King Black Dragon'),
(50, 'Kraken'),
(51, 'Kree''Arra'),
(52, 'K''ril Tsutsaroth'),
(53, 'Lunar Chests'),
(54, 'Mad Angel'),
(55, 'Maggot King'),
(56, 'Mimic'),
(57, 'Nex'),
(58, 'Nightmare'),
(59, 'Phosani''s Nightmare'),
(60, 'Obor'),
(61, 'Phantom Muspah'),
(62, 'Sarachnis'),
(63, 'Scorpia'),
(64, 'Scurrius'),
(65, 'Shellbane Gryphon'),
(66, 'Skotizo'),
(67, 'Sol Heredit'),
(68, 'Spindel'),
(69, 'Tempoross'),
(70, 'The Gauntlet'),
(71, 'The Corrupted Gauntlet'),
(72, 'The Hueycoatl'),
(73, 'The Leviathan'),
(74, 'The Royal Titans'),
(75, 'The Whisperer'),
(76, 'Theatre of Blood'),
(77, 'Theatre of Blood: Hard Mode'),
(78, 'Thermonuclear Smoke Devil'),
(79, 'Tombs of Amascut'),
(80, 'Tombs of Amascut: Expert Mode'),
(81, 'TzKal-Zuk'),
(82, 'TzTok-Jad'),
(83, 'Vardorvis'),
(84, 'Venenatis'),
(85, 'Vet''ion'),
(86, 'Vorkath'),
(87, 'Wintertodt'),
(88, 'Yama'),
(89, 'Zalcano'),
(90, 'Zulrah');